In [4]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [8]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(a[0])
[1,  2,  3,  4,]

[1 2 3 4]


[1, 2, 3, 4]

In [11]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [12]:
import numpy as np
a = np.array([1, 2, 3,])
print(a)

[1 2 3]


In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.ones(2)

array([1., 1.])

In [15]:
# Membuat array kosong dengan 2 elemen
np.empty(2)

array([1., 1.])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [18]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
x = np.ones(2, dtype=np.int64)
print(x)

[1 1]


In [20]:
arr =np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)

[2 1 5 3 7 4 6 8]


In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [25]:
array_example.ndim

3

In [26]:
array_example.size

24

In [27]:
array_example.shape

(3, 2, 4)

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [ ]:
data = np.array([1, 2, 3])
data[1]

2

In [ ]:
data[0:2]


array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [ ]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [ ]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
print(a[b])

[1 2 3 4]


In [ ]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2 = a.copy()
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * data

array([1, 4])

In [ ]:
data / data

array([1., 1.])

In [ ]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [ ]:
data.max()

2.0

In [ ]:
data.min()

1.0

In [ ]:
data.sum()

3.0

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],[0.54627315, 0.05093587, 0.40067661, 0.55645993],[0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()

4.8595784

In [ ]:
a.min()

0.05093587

In [ ]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0, 1]

2

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
data.max()

6

In [ ]:
data.min()

1

In [ ]:
data.sum()

21

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 5, 6])

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.52450341, 0.75168262, 0.73074761])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
rng.random((3, 2))

array([[0.86899188, 0.77420684],
       [0.35483498, 0.28382049],
       [0.40298698, 0.68573051]])

In [ ]:
rng.integers(5, size=(2, 4))

array([[4, 0, 3, 0],
       [4, 4, 4, 2]])

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [ ]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]
